version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  tasks:
    build: ./tasks
    container_name: tasks
    environment:
      - MONGO_URI=mongodb://mongo:27017/tasks_db
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  user_service:
    build: ./user_service
    container_name: user_service
    environment:
      - MONGO_URI=mongodb://mongo:27017/users_db
    ports:
      - "5001:5001"
    depends_on:
      - mongo

volumes:
  mongo_data:
